apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: &app-name go-payment-hpa
  namespace: test-a
  labels:
    app: *app-name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-payment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30