// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: internal/core/proto/pod/pod.proto

package pod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IpAddress        string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	PodName          string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	AvailabilityZone string                 `protobuf:"bytes,3,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	GrpcHost         string                 `protobuf:"bytes,4,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	Version          string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	mi := &file_internal_core_proto_pod_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_pod_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_pod_pod_proto_rawDescGZIP(), []int{0}
}

func (x *PodInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PodInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodInfo) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *PodInfo) GetGrpcHost() string {
	if x != nil {
		return x.GrpcHost
	}
	return ""
}

func (x *PodInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PodInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInfoRequest) Reset() {
	*x = PodInfoRequest{}
	mi := &file_internal_core_proto_pod_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfoRequest) ProtoMessage() {}

func (x *PodInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_pod_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfoRequest.ProtoReflect.Descriptor instead.
func (*PodInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_pod_pod_proto_rawDescGZIP(), []int{1}
}

type PodInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodInfo       *PodInfo               `protobuf:"bytes,1,opt,name=podInfo,proto3" json:"podInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInfoResponse) Reset() {
	*x = PodInfoResponse{}
	mi := &file_internal_core_proto_pod_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfoResponse) ProtoMessage() {}

func (x *PodInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_pod_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfoResponse.ProtoReflect.Descriptor instead.
func (*PodInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_pod_pod_proto_rawDescGZIP(), []int{2}
}

func (x *PodInfoResponse) GetPodInfo() *PodInfo {
	if x != nil {
		return x.PodInfo
	}
	return nil
}

var File_internal_core_proto_pod_pod_proto protoreflect.FileDescriptor

var file_internal_core_proto_pod_pod_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x64, 0x2f, 0x70, 0x6f, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x70, 0x63, 0x48,
	0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x10, 0x0a,
	0x0e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x35, 0x0a, 0x0f, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x70, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70,
	0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x19, 0x5a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_core_proto_pod_pod_proto_rawDescOnce sync.Once
	file_internal_core_proto_pod_pod_proto_rawDescData []byte
)

func file_internal_core_proto_pod_pod_proto_rawDescGZIP() []byte {
	file_internal_core_proto_pod_pod_proto_rawDescOnce.Do(func() {
		file_internal_core_proto_pod_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_proto_pod_pod_proto_rawDesc), len(file_internal_core_proto_pod_pod_proto_rawDesc)))
	})
	return file_internal_core_proto_pod_pod_proto_rawDescData
}

var file_internal_core_proto_pod_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_core_proto_pod_pod_proto_goTypes = []any{
	(*PodInfo)(nil),         // 0: PodInfo
	(*PodInfoRequest)(nil),  // 1: PodInfoRequest
	(*PodInfoResponse)(nil), // 2: PodInfoResponse
}
var file_internal_core_proto_pod_pod_proto_depIdxs = []int32{
	0, // 0: PodInfoResponse.podInfo:type_name -> PodInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_core_proto_pod_pod_proto_init() }
func file_internal_core_proto_pod_pod_proto_init() {
	if File_internal_core_proto_pod_pod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_proto_pod_pod_proto_rawDesc), len(file_internal_core_proto_pod_pod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_core_proto_pod_pod_proto_goTypes,
		DependencyIndexes: file_internal_core_proto_pod_pod_proto_depIdxs,
		MessageInfos:      file_internal_core_proto_pod_pod_proto_msgTypes,
	}.Build()
	File_internal_core_proto_pod_pod_proto = out.File
	file_internal_core_proto_pod_pod_proto_goTypes = nil
	file_internal_core_proto_pod_pod_proto_depIdxs = nil
}
