apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-payment-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.2"
  POD_NAME: "go-payment"
  PORT: "5007"
  DB_HOST: "rds-proxy-db-arch-02.proxy-cj4aqa08ettf.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  NO_AZ: "true"
  TLS: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-02-xray-collector.default.svc.cluster.local:4317"

  SERVER_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv" #Private NO TLS
  X_APIGW_API_ID: "129t4y8eoj"
  
  #SERVER_URL_DOMAIN: "https://vpce-arch-eks-01.architecture.caradhras.io"
  #X_APIGW_API_ID: ""

  #SERVER_URL_DOMAIN: "https://go-account.architecture.caradhras.io" #Pulic
  #SERVER_URL_DOMAIN: "https://vpce-svc-acc-908671954593.architecture.caradhras.io" #vpce-03c99f9816dadaef7-s2c9mfvk.vpce-svc-07d64576b83d898d4.us-east-2.vpce.amazonaws.com
  #SERVER_HOST: "go-account.architecture.caradhras.io" # Only LOCALHOST test

  #GRPC_HOST: "dns:///svc-go-fraud.test-a.svc.cluster.local:50052" # Only for the same EKS
  GRPC_HOST: "dns:///go-fraud.architecture.caradhras.io:50052"
