apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: &app-name ss-sa-go-payment
  namespace: test-a
  labels:
    app: *app-name
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: sa-go-payment